### ISSUE TITLE
Write tutorial for developers

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#145]
Complete https://github.com/fixstars/clpy/wiki/Developer's-tutorial

**Comment by LWisteria** [comment]
@snsato please take this. Write the document in English but you can leave memo here in any language.

チュートリアル自体は英語で書いてほしいですが、このチケットにメモやコメントを残したりするのは日本語でも大丈夫です

**Comment by snsato** [comment]
@LWisteria 承知しました。

**Comment by snsato** [comment]
1. Setup CUDA and OpenCL ready enviroment

CUDAとOpenCLは既にインストールされている。

- CUDA:/usr/local/cuda
- OpenCL:/usr/local/cuda/CL

2. Try Chainer MNIST example with CuPy

CuPY is a NumPy-compatible matrix library accelerated by CUDA.

そのため、CuPYを用いるには初めにPythonを利用できるようにする必要がある。

任意のバージョンのpythonを使うことができると便利である（ClPyはpython 3.6.5が推奨されているため）。
そのため、pyenvを導入する。

pyenvの導入には2つのステップがある。
1つ目のステップはpyenvをgithubからcloneすることである。

```
git clone git://github.com/yyuu/pyenv.git ~/.pyenv 
```

2つ目のステップはpyenvのパスを通すためにbash_profileを編集することである。

bash_profileに以下の文言を追記する。

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

```
そののちにbash_profileの変更を適用するために以下のコマンドを実行する

```
source ~/.bash_profile
```

するとpyenvコマンドが利用できるようになっている。

ClPyで推奨されているpythonのバージョンは3.6.5のため, pyenvでバージョン3.6.5のpythonを使用できるようにする。
以下の一連のコマンドを実行することでpython 3.6.5を使用できるようになる。

```
pyenv install 3.6.5
pyenv global 3.6.5
```

これまででpython 3.6.5を使用できるようになった。
しかし、このままだと3.6.5の環境が1つのみであり、CuPYとClPyの環境を同じ環境で扱わなければいけなくなる。
しかし、これらの環境は分けて構築したい。
そのため、venvと呼ばれる機能を使用し仮想環境を構築する。
venvを以下のように使用することで同じpythonのバージョンで複数の環境を構築することができる。
環境を保存するディレクトリが必要となる？

例）環境Nameの作成（Nameは適当な名称をつける)

```
mkdir Name
python -m venv Name
```
作成した仮想環境を使用するには以下のコマンドを実行する

```
source /path/to/Name/bin/activate
```
作成した仮想環境から出るには以下のコマンドを実行する

```
deactivate
``` 

これまでの操作で任意のpythonのバージョンで複数の環境を作成することができるようになった。

作成した仮想環境においてCuPYとChainerの導入を行う。
CuPY,Chainerともにpipからインストールを行うことができる。
以下のコマンドでインストールを行う。
（CuPYを用いるためにnumpyが必要なため、numpyもインストールする)
（ただし、CuPYはインストールするマシンで使用されているCUDAのバージョンによって適したCuPYを入れることができる。titanv(このガイドを書く上で使用したマシン)ではCUDA9.2が使用されているため、 cupy-cuda92（CUDA9.2に適したCuPY)をインストールする)
（ただし、ClPyにおいてChainerのバージョンは3.3.0を使用することが推奨されているため、Chainerのバージョンは最新版ではなく3.3.0をインストールするようにする）

```
pip install numpy
pip install cupy-cuda92
pip install chainer==3.3.0
```

ChainerのMNIST exampleを実行するために、MNISTのプログラムを入手する。
そのために、githubのChainerレポジトリをcloneする。
以下のコマンドでcloneを行う。
（ただし、ClPyにおいてChainerのバージョンは3.3.0を使用することが推奨されているため、Chainerのバージョンは最新版ではなく3.3.0をcloneするようにする)

```
git clone -b v3.3.0 https://github.com/chainer/chainer.git
```

Chainerをcloneしたら、次にChainerレポジトリ内に入ってMNIST exampleを実行する。
MNISTは chainer/examples/mnist に存在する。
上記ディレクトリまで移動したのちに以下のコマンドを入力することでMNISTを実行することができる。
(-g:どのGPUで実行するかを決めるオプション、デフォルトは0)

```
python train_mnist.py -g 0
```
ここで「matplotlibがないから入れてください」と言われるので、インストール（以下のコマンドで行う）すると、別のエラーが出てくることがある。
その場合はMNISTの実行時に --noplot オプションをつけるとよい。

```
pip install matplotlib
```
--noplotオプションをつけた場合

```
python train_mnist.py -g 0 --noplot
```

3. Install ClPy and run simple test

ClPyの導入を行う。

ClPYのREADMEにも書いてあるが、ここで今一度説明する。

ClPyはOpenCLとLLVM/ClangとCLBlastの3つを必要とする。
そのため、始めにこれらの3つをインストールする。

1)OpenCL

既にインストールされている（titanvでは）ため、bash_profileに以下の記述を追記するだけでよい。

```
export C_INCLUDE_PATH=/usr/local/cuda/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/usr/local/cuda/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/usr/local/cuda/lib64:${LIBRARY_PATH}
```
2)LLVM/Clang
これも同様に既にインストールされているため、bash_profileに以下の記述を追記するだけでよい。なお、自身でソースからインストールすることもできる。

```
export PATH=/usr/lib/llvm-5.0/include:usr/local/include:${PATH}
export LIBRARY_PATH=/usr/lib/llvm-5.0/lib:usr/local/lib:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/lib/llvm-5.0/lib:usr/local/lib:${LD_LIBRARY_PATH}
```
3)CLBlast
CLBlastはインストールされていないので、自身で入手する必要がある。
ClPyによりバージョン1.4.1以降を用いることが推奨されている。
今回はバージョン1.4.1のものを使用する。

CLBlastを次のurlから入手する。(https://github.com/CNugteren/CLBlast/releases/tag/1.4.1) ダウンロードするのは Source code.tar.gz が良いと思う。

入手したファイルを解凍し、適当なディレクトリに移動させる。
移動させた後に解凍したファイル（CLBlast-1.4.1）に移動する。
CLBlastを使用できるようにするために以下のコマンドを行う。

```
mkdir build
cd build
cmake ..
make
```
すると、buildディレクトリ内にプログラムが現れる。
CLBlastをClPYで使用できるようにするために以下の記述を.bash_profileに追記する。

```
export C_INCLUDE_PATH=~/workspace/CLBlast-1.4.1/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=~/workspace/CLBlast-1.4.1/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=~/workspace/CLBlast-1.4.1/build:${LIBRARY_PATH}
export LD_LIBRARY_PATH=~/workspace/CLBlast-1.4.1/build:${LD_LIBRARY_PATH}
```
以上のbash_profileの変更を適用するために以下のコマンドを実行する

```
source ~/.bash_profile
```

次にClPY用の仮想環境を作成する。CuPY用仮想環境を作成した時と同様に作成すればよい。

以上でClPYを導入する準備が整ったので、ClPyの導入に入る。

始めにgithubからClPyをcloneする。以下のコマンドで行う。

```
git clone https://github.com/fixstars/clpy.git
```

cloneが終わったら、clpyディレクトリ内に移動する。
numpyとcythonが必要となるため、pipでインストールを行う。

```
pip install numpy
pip install cython
```

その後にClPyディレクトリ内で以下のコマンドを実行するとClPyのインストールが行える。

```
python setup.py install
```

ClPyのインストールが無事終わったので、簡単なテストを行う。
テストを行う際にpytestが必要となるので、pipでインストールを行う。

```
pip install pytest
```

pyclディレクトリ内に複数のテストプログラムがあるので、行いたいテストを以下のコマンドで実行するとよい。

```
cd tests/you/want
python -m pytest test_you_want.py
```

なお各プログラムの実行結果が https://github.com/fixstars/clpy/wiki/cupy_test_example_results に記述されている。

4. Try Chainer example with ClPy

ChainerのMNISTをClPyで行う流れを説明する。

2.CuPYでcloneしたchainerディレクトリに移動する。この際仮想環境はclpyインストール時のものとする。
MNISTがあるディレクトリ( chainer/examples/mnist )まで移動する。
上記ディレクトリまで移動したのちに以下のコマンドを入力することでMNISTをClPY実行することができる。
(-m clpy:CuPYをClPyに変更する)

```
python -m clpy train_mnist.py -g 0

```

以上でMNISTをClPYで実行することができる。同様に様々なCuPYで記述されたプログラムをClPyで実行することができる。
( https://github.com/fixstars/clpy/wiki/chainer_test_example_results#example )

**Comment by snsato** [comment]
清書・間違い探ししつつ英文に直していきます

**Comment by snsato** [comment]
This document is a tutorial for who is going to join ClPy development.

## 1. Setup CUDA and OpenCL ready enviroment

Download and install CUDA from this url ( https://developer.nvidia.com/cuda-downloads ).
OpenCL is embedded in CUDA.
Since the downloading / installing method is written in the link destination, omit it.

Each pass is shown below.

- CUDA:/usr/local/cuda
- OpenCL:/usr/local/cuda/CL

## 2. Try Chainer MNIST example with CuPy

CuPy is a NumPy-compatible matrix library accelerated by CUDA.
Therefore, Python is necessary to use CuPY.

It is convenient to be able to use any version of Python, because the version of Python recommended by your application may be different.
To use any version of Python, introduce pyenv.

There are two steps to introducing pyenv.
The first step is to clone pyenv from github.

```
git clone git://github.com/yyuu/pyenv.git ~/.pyenv 
```

The second step is to edit bash_profile to pass the pyenv path.

You should set following environment variables.

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

You should execute the following command to apply the change of bash_profile.

```
source ~/.bash_profile
```

Then the pyenv command is available.

Since python version recommended for ClPy is 3.6.5, use Python 3.6.5.
You can use Python 3.6.5 by executing the following commands.

```
pyenv install 3.6.5
pyenv global 3.6.5
```

You can now use Python 3.6.5.
However, there is only one environment of Python 3.6.5, and the environment of CuPy and ClPy has to be handled in the same environment.
However, these environments should be built separately.

Therefore, you use venv built in Python to build virtual environment.
An example of building a virtual environment is shown below.

### Example) Creation of Environment Name (Name is an appropriate name indicating usage)

```
mkdir Name
python -m venv Name
```

To use the created virtual environment, execute the following command.

```
source /path/to/Name/bin/activate
```

To get out of the created virtual environment, execute the following command.

```
deactivate
``` 

With the above operation, it is now possible to create multiple environments with any version of Python.

Introducing CuPy and Chainer in virtual environment.
Both CuPy and Chainer can install from pip.
Install with the following command.

- Since numPy is required to use CuPy, install numpy as well.
- CuPy is suited to the version of CUDA used on the machine, since CUDA 9.2 is used in titanv (the machine used to write this guide), install cupy-cuda 92.
- As it is recommended to use 3.3.0 for Chainer version in ClPy, make sure to install 3.3.0 instead of the latest version of Chainer.

```
pip install numpy
pip install cupy-cuda92
pip install chainer==3.3.0
```

To run Chainer's MNIST example, get the MNIST program.
For that, clone Chainer from github.
Clone with the following command.

- As it is recommended to use 3.3.0 for Chainer version in ClPy, we will clone 3.3.0 instead of the latest version of Chainer.

```
git clone -b v3.3.0 https://github.com/chainer/chainer.git
```

Next, enter the Chainer repository and run MNIST example.
MNIST exists in /path/to/chainer/examples/mnist.
MNIST can be executed by moving to the above directory and then inputting the following command.

- -g: An option to decide which GPU to run. The default is -1.

```
python train_mnist.py -g 0
```

Here's a warning from the program that " matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.", so installing matplotlib (done with the following command) and running the program again may cause another error.
In that case, you can attach the --noplot option.

```
pip install matplotlib
```
With the --noplot option

```
python train_mnist.py -g 0 --noplot
```

## 3. Install ClPy and run simple test

ClPy requires OpenCL, LLVM / Clang and CLBlast.
Therefore, install these three at the beginning.

### 1 OpenCL

Since OpenCL is embedded in CUDA, you only need to set following environment variables to bash_profile.

```
export C_INCLUDE_PATH=/usr/local/cuda/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/usr/local/cuda/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/usr/local/cuda/lib64:${LIBRARY_PATH}
```

### 2 LLVM/Clang

If it is already installed in (like titanv), you only need to set following environment variables to bash_profile. If not, you can install from source yourself.

```
export PATH=/usr/lib/llvm-5.0/include:usr/local/include:${PATH}
export LIBRARY_PATH=/usr/lib/llvm-5.0/lib:usr/local/lib:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/lib/llvm-5.0/lib:usr/local/lib:${LD_LIBRARY_PATH}
```

### 3 CLBlast

CLBlast is not installed, so you need to install it.
It is recommended to use CLBlast version 1.4.1 or later with ClPy.
This time use version 1.4.1.

Obtain CLBlast from url (https://github.com/CNugteren/CLBlast/releases/tag/1.4.1).
Download Source code (tar.gz).

Extract the obtained file and move it to the appropriate directory.
Move to file (CLBlast - 1.4.1).
In order to be able to use CLBlast, do the following command.

```
mkdir build
cd build
cmake ..
make
```

Then the program appears in the build directory.
Set following environment variables to bash_profile so that CLBlast can be used with ClPY.

```
export C_INCLUDE_PATH=/path/to/CLBlast-1.4.1/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/path/to/CLBlast-1.4.1/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/path/to/CLBlast-1.4.1/build:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/path/to/CLBlast-1.4.1/build:${LD_LIBRARY_PATH}
```

Execute the following command to apply the above bash_profile changes.

```
source ~/.bash_profile
```

Next, create a virtual environment for ClPY. You can create it just as you did when creating the virtual environment.
Subsequently, introduction of ClPy is started.
First, clone ClPy from github. Use the following command.

```
git clone https://github.com/fixstars/clpy.git
```

After clone, move to the clpy directory.
Since numpy and cython are necessary, install with pip.

```
pip install numpy
pip install cython
```

After that, you can install ClPy by executing the following command in the clpy directory.

```
python setup.py install
```

When ClPy installation is completed successfully, do a simple test.
Since pytest is necessary for testing, install with pip.

```
pip install pytest
```

Since there are multiple test programs in the clpy directory, you can execute the test you wish to perform with the following command.

```
cd /path/to/clpy/tests/you/want
python -m pytest test_you_want.py
```

The execution result of each test is displayed in https://github.com/fixstars/clpy/wiki/cupy_test_example_results.

## 4. Try Chainer example with ClPy

Move to chainer directory. At this time, the virtual environment is for clpy.
Move to the directory where MNIST is located (/ path / to / chainer / examples / mnist).
After moving to the above directory, you can run MNIST with ClPy by entering the following command.
- -m clpy: Change CuPY to ClPy

```
python -m clpy train_mnist.py -g 0
```

With this, MNIST can be executed with ClPY. Likewise, programs written with various CuPY can be executed with ClPy

( https://github.com/fixstars/clpy/wiki/chainer_test_example_results#example ).

**Comment by snsato** [comment]
@LWisteria 英語訳の第一稿ができました。レビューをよろしくお願いいたします。

**Comment by neko-suki** [comment]
> Therefore, Python is necessary to use CuPY.

This should be "CuPy".

**Comment by snsato** [comment]
ありがとうございます、修正させていただきます。

**Comment by snsato** [comment]
同様にClPyやPythonのタイポもいくつかあったので修正します。

**Comment by snsato** [comment]
This document is a tutorial for who is going to join ClPy development.

## 1. Setup CUDA and OpenCL ready environment

Download and install CUDA from this url ( https://developer.nvidia.com/cuda-downloads ).
OpenCL is embedded in CUDA.
Since the downloading / installing method is written in the link destination, omit it.

Each pass is shown below.

- CUDA:/usr/local/cuda
- OpenCL:/usr/local/cuda/include/CL

## 2. Try Chainer MNIST example with CuPy

CuPy is a NumPy-compatible matrix library accelerated by CUDA.
Therefore, Python is necessary to use CuPy.

It is convenient to be able to use any version of Python, because the version of Python recommended by your application may be different.
To use any version of Python, introduce pyenv.

There are two steps to introducing pyenv.
The first step is to clone pyenv from github.

```
git clone git://github.com/yyuu/pyenv.git ~/.pyenv 
```

The second step is to edit bash_profile to pass the pyenv path.

You should set following environment variables.

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

You should execute the following command to apply the change of bash_profile.

```
source ~/.bash_profile
```

Then the pyenv command is available.

Since Python version recommended for ClPy is 3.6.5, use Python 3.6.5.
You can use Python 3.6.5 by executing the following commands.

```
pyenv install 3.6.5
pyenv global 3.6.5
```

You can now use Python 3.6.5.
However, there is only one environment of Python 3.6.5, and the environments of CuPy and ClPy has to be handled in the same environment.
However, these environments should be built separately.

Therefore, you use venv built in Python to build virtual environment.
An example of building a virtual environment is shown below.

### Example) Creation of virtual environment 'Name' (Name is an appropriate name indicating usage)

```
mkdir Name
python -m venv Name
```

To use the created virtual environment, execute the following command.

```
source /path/to/Name/bin/activate
```

To get out of the created virtual environment, execute the following command.

```
deactivate
``` 

With the above operation, it is now possible to create multiple environments with any version of Python.

Introducing CuPy and Chainer in virtual environment.
Both CuPy and Chainer can install from pip.
Install with the following commands.

- Since NumPy is required to use CuPy, install NumPy as well.
- CuPy is suited to the version of CUDA used on the machine, since CUDA 9.2 is used in titanv (the machine used to write this guide), install cupy-cuda92.
- As it is recommended to use 3.3.0 for Chainer version in ClPy, make sure to install 3.3.0 instead of the latest version of Chainer.

```
pip install numpy
pip install cupy-cuda92
pip install chainer==3.3.0
```

To run Chainer's MNIST example, get the MNIST program.
For that, clone Chainer from github.
Clone with the following command.

- As it is recommended to use 3.3.0 for Chainer version in ClPy, clone 3.3.0 instead of the latest version of Chainer.

```
git clone -b v3.3.0 https://github.com/chainer/chainer.git
```

Next, enter the Chainer repository and run MNIST example.
MNIST exists in /path/to/chainer/examples/mnist.
MNIST can be executed by moving to the above directory and then inputting the following command.

- -g: An option to decide which GPU to run. The default is -1.

```
python train_mnist.py -g 0
```

Here's a warning from the program that " matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.", so installing matplotlib (done with the following command) and running the program again may cause another error.
In that case, you can attach the --noplot option.

```
pip install matplotlib
```
With the --noplot option

```
python train_mnist.py -g 0 --noplot
```

## 3. Install ClPy and run simple test

ClPy requires OpenCL, LLVM/Clang and CLBlast.
Therefore, install these three at the beginning.

### 1) OpenCL

Since OpenCL is embedded in CUDA, you only need to set following environment variables to bash_profile.

```
export C_INCLUDE_PATH=/usr/local/cuda/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/usr/local/cuda/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/usr/local/cuda/lib64:${LIBRARY_PATH}
```

### 2) LLVM/Clang

If it is already installed in (like titanv), you only need to set following environment variables to bash_profile. If not, you can install from source yourself.

```
export PATH=/usr/lib/llvm-5.0/include:/usr/local/include:${PATH}
export LIBRARY_PATH=/usr/lib/llvm-5.0/lib:/usr/local/lib:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/lib/llvm-5.0/lib:/usr/local/lib:${LD_LIBRARY_PATH}
```

### 3) CLBlast

CLBlast is not installed, so you need to install it.
It is recommended to use CLBlast version 1.4.1 or later with ClPy.
This time use version 1.4.1.

Obtain CLBlast from url (https://github.com/CNugteren/CLBlast/releases/tag/1.4.1).
Download Source code (tar.gz).

Extract the obtained file and move it to the appropriate directory.
Move to file (CLBlast - 1.4.1).
In order to be able to use CLBlast, do the following command.

```
mkdir build
cd build
cmake ..
make
```

Then the program appears in the build directory.
Set following environment variables to bash_profile so that CLBlast can be used with ClPy.

```
export C_INCLUDE_PATH=/path/to/CLBlast-1.4.1/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/path/to/CLBlast-1.4.1/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/path/to/CLBlast-1.4.1/build:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/path/to/CLBlast-1.4.1/build:${LD_LIBRARY_PATH}
```

Execute the following command to apply the above bash_profile changes.

```
source ~/.bash_profile
```

Next, create a virtual environment for ClPy. You can create it just as you did when creating the virtual environment 'Name'.
Subsequently, introduction of ClPy is started.
First, clone ClPy from github. Use the following command.

```
git clone https://github.com/fixstars/clpy.git
```

After clone, move to the clpy directory.
Since NumPy and Cython are necessary, install with pip.

```
pip install numpy
pip install cython
```

After that, you can install ClPy by executing the following command in the clpy directory.

```
python setup.py install
```

When ClPy installation is completed successfully, do a simple test.
Since pytest is necessary for testing, install with pip.

```
pip install pytest
```

Since there are multiple test programs in the clpy directory, you can execute the test you wish to perform with the following command.

```
cd /path/to/clpy/tests/you/want
python -m pytest test_you_want.py
```

The execution result of each test is displayed in https://github.com/fixstars/clpy/wiki/cupy_test_example_results.

## 4. Try Chainer example with ClPy

Chainer can install from pip.
Install with the following command.

```
pip install chainer==3.3.0
```

Move to chainer directory. At this time, the virtual environment is for ClPy.
Move to the directory where MNIST is located (/path/to/chainer/examples/mnist).
After moving to the above directory, you can run MNIST with ClPy by entering the following command.
- -m clpy: Change CuPy to ClPy

```
python -m clpy train_mnist.py -g 0
```

With this, MNIST can be executed with ClPy. Likewise, programs written with various CuPy can be executed with ClPy

( https://github.com/fixstars/clpy/wiki/chainer_test_example_results#example ).

**Comment by snsato** [comment]
typoを修正しました(まだtypoが潜んでいないか怖い)

**Comment by LWisteria** [comment]
> github.com/yyuu/pyenv.git

は`github.com/pyenv/pyenv.git`ですね。

あと、環境の切り分けを手動でやってますが、pyenv-virtualenvを使うほうが楽なので、そっちを使ってみる方に変えてもらうことはできますか？

**Comment by LWisteria** [comment]
後は良さそうです。

**Comment by snsato** [comment]
This document is a tutorial for who is going to join ClPy development.

## 1. Setup CUDA and OpenCL ready environment

Download and install CUDA from this url ( https://developer.nvidia.com/cuda-downloads ).
OpenCL is embedded in CUDA.
Since the downloading / installing method is written in the link destination, omit it.

Each pass is shown below.

- CUDA:/usr/local/cuda
- OpenCL:/usr/local/cuda/include/CL

## 2. Try Chainer MNIST example with CuPy

CuPy is a NumPy-compatible matrix library accelerated by CUDA.
Therefore, Python is necessary to use CuPy.

It is convenient to be able to use any version of Python, because the version of Python recommended by your application may be different.
To use any version of Python, introduce pyenv.

There are two steps to introducing pyenv.
The first step is to clone pyenv from github.

```
git clone git://github.com/pyenv/pyenv.git ~/.pyenv 
```

The second step is to edit bash_profile to pass the pyenv path.

You should set following environment variables.

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

You should execute the following command to apply the change of bash_profile.

```
source ~/.bash_profile
```

Then the pyenv command is available.

Since Python version recommended for ClPy is 3.6.5, use Python 3.6.5.
You can use Python 3.6.5 by executing the following commands.

```
pyenv install 3.6.5
pyenv global 3.6.5
```

You can now use Python 3.6.5.
However, there is only one environment of Python 3.6.5, and the environments of CuPy and ClPy has to be handled in the same environment.
However, these environments should be built separately.

Therefore, you use pyenv's plugin, pyenv-virtualenv, to build a virtual environment.

Enable to use pyenv-virtualenv.

Clone pyenv-virtualenv by executing the following command.


```
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
```

You should set following environment variables to bash_profile.

```
eval "$(pyenv virtualenv-init -)"
```

You should execute the following command to apply the change of bash_profile.

```
source ~/.bash_profile
```

With this, you can use pyenv-virtualenv.

### Example) Creation of virtual environment 'Name' (Name is an appropriate name indicating usage)

```
pyenv virtualenv 3.6.5 Name
```

The environment Name is created with the above.

To confirm that it was created, execute the following command.

```
pyenv versions
```

To work in the created virtual environment Name, execute the following command.

```
pyenv shell Name
```

With the above operation, it is now possible to create multiple environments with any version of Python.

Introducing CuPy and Chainer in virtual environment.
Both CuPy and Chainer can install from pip.
Install with the following commands.

- Since NumPy is required to use CuPy, install NumPy as well.
- CuPy is suited to the version of CUDA used on the machine, since CUDA 9.2 is used in titanv (the machine used to write this guide), install cupy-cuda92.
- As it is recommended to use 3.3.0 for Chainer version in ClPy, make sure to install 3.3.0 instead of the latest version of Chainer.

```
pip install numpy
pip install cupy-cuda92
pip install chainer==3.3.0
```

To run Chainer's MNIST example, get the MNIST program.
For that, clone Chainer from github.
Clone with the following command.

- As it is recommended to use 3.3.0 for Chainer version in ClPy, clone 3.3.0 instead of the latest version of Chainer.

```
git clone -b v3.3.0 https://github.com/chainer/chainer.git
```

Next, enter the Chainer repository and run MNIST example.
MNIST exists in /path/to/chainer/examples/mnist.
MNIST can be executed by moving to the above directory and then inputting the following command.

- -g: An option to decide which GPU to run. The default is -1.

```
python train_mnist.py -g 0
```

Here's a warning from the program that " matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.", so installing matplotlib (done with the following command) and running the program again may cause another error.
In that case, you can attach the --noplot option.

```
pip install matplotlib
```
With the --noplot option

```
python train_mnist.py -g 0 --noplot
```

## 3. Install ClPy and run simple test

ClPy requires OpenCL, LLVM/Clang and CLBlast.
Therefore, install these three at the beginning.

### 1) OpenCL

Since OpenCL is embedded in CUDA, you only need to set following environment variables to bash_profile.

```
export C_INCLUDE_PATH=/usr/local/cuda/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/usr/local/cuda/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/usr/local/cuda/lib64:${LIBRARY_PATH}
```

### 2) LLVM/Clang

If it is already installed in (like titanv), you only need to set following environment variables to bash_profile. If not, you can install from source yourself.

```
export PATH=/usr/lib/llvm-5.0/include:/usr/local/include:${PATH}
export LIBRARY_PATH=/usr/lib/llvm-5.0/lib:/usr/local/lib:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/lib/llvm-5.0/lib:/usr/local/lib:${LD_LIBRARY_PATH}
```

### 3) CLBlast

CLBlast is not installed, so you need to install it.
It is recommended to use CLBlast version 1.4.1 or later with ClPy.
This time use version 1.4.1.

Obtain CLBlast from url (https://github.com/CNugteren/CLBlast/releases/tag/1.4.1).
Download Source code (tar.gz).

Extract the obtained file and move it to the appropriate directory.
Move to file (CLBlast - 1.4.1).
In order to be able to use CLBlast, do the following command.

```
mkdir build
cd build
cmake ..
make
```

Then the program appears in the build directory.
Set following environment variables to bash_profile so that CLBlast can be used with ClPy.

```
export C_INCLUDE_PATH=/path/to/CLBlast-1.4.1/include:${C_INCLUDE_PATH}
export CPLUS_INCLUDE_PATH=/path/to/CLBlast-1.4.1/include:${CPLUS_INCLUDE_PATH}
export LIBRARY_PATH=/path/to/CLBlast-1.4.1/build:${LIBRARY_PATH}
export LD_LIBRARY_PATH=/path/to/CLBlast-1.4.1/build:${LD_LIBRARY_PATH}
```

Execute the following command to apply the above bash_profile changes.

```
source ~/.bash_profile
```

Next, create a virtual environment for ClPy. You can create it just as you did when creating the virtual environment 'Name'.
Subsequently, introduction of ClPy is started.
First, clone ClPy from github. Use the following command.

```
git clone https://github.com/fixstars/clpy.git
```

After clone, move to the clpy directory.
Since NumPy and Cython are necessary, install with pip.

```
pip install numpy
pip install cython
```

After that, you can install ClPy by executing the following command in the clpy directory.

```
python setup.py install
```

When ClPy installation is completed successfully, do a simple test.
Since pytest is necessary for testing, install with pip.

```
pip install pytest
```

Since there are multiple test programs in the clpy directory, you can execute the test you wish to perform with the following command.

```
cd /path/to/clpy/tests/you/want
python -m pytest test_you_want.py
```

The execution result of each test is displayed in https://github.com/fixstars/clpy/wiki/cupy_test_example_results.

## 4. Try Chainer example with ClPy

Chainer can install from pip.
Install with the following command.

```
pip install chainer==3.3.0
```

Move to chainer directory. At this time, the virtual environment is for ClPy.
Move to the directory where MNIST is located (/path/to/chainer/examples/mnist).
After moving to the above directory, you can run MNIST with ClPy by entering the following command.
- -m clpy: Change CuPy to ClPy

```
python -m clpy train_mnist.py -g 0
```

With this, MNIST can be executed with ClPy. Likewise, various programs written with CuPy can be executed with ClPy

( https://github.com/fixstars/clpy/wiki/chainer_test_example_results#example ).

**Comment by snsato** [comment]
@LWisteria  pyenv-virtualenvに関してですが、環境の切り分けはこのような感じでよろしいでしょうか

（作業をするたびに ```pyenv shell Name``` で環境に入るのが良いのか、それとも ```pyenv local Name``` でディレクトリに入るだけで環境にはいれるようにするほうが良いのかの判断がつきませんでした）

**Comment by LWisteria** [comment]
はい、とりあえずこんな感じで良いと思います。

wikiに転載をお願いします。細かいところはwikiの上でみんなで作っていきましょう。

**Comment by snsato** [comment]
承知しました。

**Comment by LWisteria** [comment]
https://github.com/fixstars/clpy/wiki/Developer's-tutorial を確認しました。ありがとうございました。
