### ISSUE TITLE
pip install . does not build ultima

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#147]
According to README, we must use following command to install clpy

```
$ python setup.py install
```

However

```
$ pip install .
```

does not work because ultima is not built and installed. Why and can we fix?

**Comment by LWisteria** [comment]
@vorj do you have any ideas?

**Comment by vorj** [comment]
@LWisteria I investigated that.
When we install using `setup.py` , the install path is `/path/to/lib/python<python-version>/site-packages/clpy-<clpy-version>-py<python-version>-<target-platform>.egg` . Both `clpy` and `ultima` are installed in this directory.
However, `pip` install the package in `/path/to/lib/python<python-version>/site-packages/clpy` and ultima in `/path/to/ultima` .

I don't know how to get the `/path/to` 's path on ClPy, but we need to fix that get the path and use it to access `ultima` instead of `clpy.__path[0]__/../ultima/ultima` .

**Comment by LWisteria** [comment]
I understand. Now I make this issue as a feature request. This is not necessary but I prefer if pip install works

**Comment by vorj** [comment]
#176 solved this issue. I close it.
