### ISSUE TITLE
How can I get "llvm-config" on windows10?

### ISSUE THREAD

**Issue by mskym** [fixstars/clpy#155]
Could you give some advice please.

my environments:

> OS : windows10
> CPU : Core i7 2600
> GPU : radeon rx570 4gb
> SDK : AMD APP SDK

When I changed directory to `"/github/clpy"` and compiled `"python setup.py install"`, this error message created.

```
building ultima started
nm: `which: invalid output format
building headercvt
clang++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -O3 -pedantic-errors ultima.cpp -lclangTooling -lclangFrontendTool -lclangFrontend -lclangDriver -lclangSerialization -lclangCodeGen -lclangParse -lclangSema -lclangStaticAnalyzerFrontend -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangAnalysis -lclangARCMigrate -lclangRecwrite -lclangEdit -lclangAST -lclangLex -lclangBasic -lclang `llvm-config --libs --system-libs` -fno-rtti -o ultima
lang++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -O3 -pedantic-errors headercvt.cpp -lclangTooling -lclangFrontendTool -lclangFrontend -lclangDriver -lclangSerialization -lclangCodeGen -lclangParse -lclangSema -lclangStaticAnalyzerFrontend -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangAnalysis -lclangEdit -lclangAST -lclangLex -lclangBasic -lclang `llvm-config --libs --system-libs` -fno-rtti -o headercvt
/usr/bin/sh: llvm-config: command not found/usr/bin/sh: llvm-config: command not found
ultima.cpp:1:10: fatal error: 'clang/Frontend/ASTConsumers.h' file not found
#include "clang/Frontend/ASTConsumers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [ultima] エラー 1
.
.
(omitted)
.
.
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import clpy_setup_build
  File "C:\Users\user\Documents\GitHub\clpy\clpy_setup_build.py", line 38, in <module>
    raise RuntimeError('Building headercvt has been failed.')
RuntimeError: Building headercvt has been failed.
```
(and many other messages were created...)

As far as I see,  the first probrem is **llvm-config.exe** is not in the bin directory.
If it's true, how can I get it?

Also,  I'd like to know whether the message `ultima.cpp:1:10: fatal error: 'clang/Frontend/ASTConsumers.h' file not found` was due to absence of llvm-config.exe.

How should I do next?

Please help me...

**Comment by LWisteria** [comment]
@mskym Thank you for interesting report!

As [README](https://github.com/fixstars/clpy#recommended-system) says, we do not develop and test on Windows but only Linux (Ubuntu). In that environment, you can get `llvm-config` via `apt`.

I think `llvm-config` must be installed with clang installer on Windows, too. I recommend you check and understand how clang/llvm on Windows works before trying clpy because your reported error messages say the issue is not about clpy itself.

In anonther way, I believe you can try clpy on Ubuntu on Windows Subsystem Linux. It is more similar to our original environments so we could give you more effective advices.

@vorj do you have any ideas?

**Comment by LWisteria** [comment]
I'm closing this issue because there is no response for a long time.
When you find any new problem with this issue, please reopen at that time.
